### 服务器配置
server:
  port: 8520

### TIMO配置
project:
  captcha-open: false                         #是否开启登录验证码
  shiro:
    remember-me-timeout: 7                    #cookie记住登录信息时间，默认7天（天）
    global-session-timeout: 1800              #Session会话超时时间，默认30分钟（秒）
  upload:
    file-path: /home/phone_lib_sys/upload/     #文件上传路径，默认在项目根目录upload下


### spring配置
spring:
## 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.85.132:3306/timo?useSSL=false&characterEncoding=utf-8
#    username: root
#    password: 123456
    url: jdbc:mysql://192.168.8.65:3306/phone_library?useSSL=false&characterEncoding=utf-8
    username: root
    password: arjPfnH8u
  sec:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://47.98.46.0:5432/jinshang
    username: admin_jinshang_dev
    password: admin04131

## jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: com.crm.common.mysql.MySQLDialectUTF8
      hibernate.format_sql: false
    open-in-view: true

  ## thymeleaf模板设置
  thymeleaf:
    cache=false: false
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false

## 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB